sudo: required
services:
    -docker

before_install:
    -docker build -t seedbg/react-test -f ./client/Dockerfile.dev ./client

script:
    -docker run -e CI=true seedbg/react-test npm test


after_success:
    -docker build -t seedbg/multi-client ./client 
    -docker build -t seedbg/multi-nginx ./nginx
    -docker build -t seedbg/multi-server ./server
    -docker build -t seedbg/multi-worker ./worker

#login to docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#push to dockerhub
    - docker push seedbg/multi-client
    - docker push seedbg/multi-nginx
    - docker push seedbg/multi-server
    - docker push seedbg/multi-worker
